'use client';

import React, { useState } from 'react';
import { jsPDF } from 'jspdf';
import { Download, Loader2 } from 'lucide-react';
import { trackEvent } from '../lib/analytics';

interface AuditFinding {
  severity: 'CRITICAL' | 'HIGH' | 'MEDIUM' | 'LOW';
  name: string;
  explanation: string;
  vulnerableCode: string;
  secureCode: string;
  gitDiff?: string;
  filePath?: string;
}

interface DownloadPDFButtonProps {
  results: AuditFinding[];
  targetName: string;
}

export default function DownloadPDFButton({ results, targetName }: DownloadPDFButtonProps) {
  const [generating, setGenerating] = useState(false);

  const generatePDF = async () => {
    setGenerating(true);

    try {
      const doc = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4'
      });

      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      
      // Calculate overall risk
      const hasCritical = results.some(r => r.severity === 'CRITICAL');
      const hasHigh = results.some(r => r.severity === 'HIGH');
      const hasMedium = results.some(r => r.severity === 'MEDIUM');
      
      let overallRisk = 'CLEAN';
      let riskColor = [16, 185, 129]; // Emerald
      
      if (hasCritical) {
        overallRisk = 'CRITICAL';
        riskColor = [239, 68, 68]; // Red
      } else if (hasHigh) {
        overallRisk = 'HIGH';
        riskColor = [249, 115, 22]; // Orange
      } else if (hasMedium) {
        overallRisk = 'MEDIUM';
        riskColor = [234, 179, 8]; // Yellow
      } else if (results.length > 0) {
        overallRisk = 'LOW';
        riskColor = [59, 130, 246]; // Blue
      }

      // Helper: Draw Header & Footer
      const drawHeaderFooter = (pageNum: number, totalPages: number) => {
        // Top branding bar
        doc.setFillColor(24, 24, 27); // Zinc 900
        doc.rect(0, 0, pageWidth, 20, 'F');
        
        doc.setFillColor(16, 185, 129); // Emerald 500
        doc.rect(0, 20, pageWidth, 1.5, 'F');

        // Header Text
        doc.setTextColor(255, 255, 255);
        doc.setFont('Helvetica', 'bold');
        doc.setFontSize(10);
        doc.text('BUGZ AUTONOMOUS SECURITY AUDIT REPORT', 15, 12.5);

        // Footer Bar
        doc.setFillColor(245, 245, 247); // Light Zinc
        doc.rect(0, pageHeight - 15, pageWidth, 15, 'F');
        doc.setDrawColor(228, 228, 231);
        doc.line(0, pageHeight - 15, pageWidth, pageHeight - 15);

        doc.setTextColor(113, 113, 122); // Zinc 500
        doc.setFont('Helvetica', 'normal');
        doc.setFontSize(8);
        doc.text('Confidential - Generated by BugZ Security Engine', 15, pageHeight - 8);
        doc.text(`Page ${pageNum} of ${totalPages}`, pageWidth - 30, pageHeight - 8);
      };

      // PAGE 1: COVER & EXECUTIVE SUMMARY
      drawHeaderFooter(1, 2);

      // Document Title
      doc.setTextColor(24, 24, 27);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(22);
      doc.text('Vulnerability Analysis Report', 15, 38);

      // Subtitle
      doc.setTextColor(113, 113, 122);
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(11);
      doc.text('Automated codebase security scanner report and generated remediation patches.', 15, 44);

      // Metadata Box
      doc.setFillColor(244, 244, 245); // Zinc 100
      doc.setDrawColor(228, 228, 231);
      doc.rect(15, 52, pageWidth - 30, 42, 'FD');

      doc.setTextColor(39, 39, 42);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('SCAN METADATA', 20, 59);

      doc.setFont('Helvetica', 'normal');
      doc.setTextColor(82, 82, 91);
      doc.text('Target Module:', 20, 67);
      doc.text('Date & Time:', 20, 73);
      doc.text('Engine Version:', 20, 79);
      doc.text('Scan Identifier:', 20, 85);

      doc.setTextColor(24, 24, 27);
      doc.text(targetName || 'Manual Raw Snippet', 50, 67);
      doc.text(new Date().toUTCString(), 50, 73);
      doc.text('Gemini 2.5 Flash', 50, 79);
      doc.text(`BZ-AUDIT-${Math.random().toString(36).substring(2, 10).toUpperCase()}`, 50, 85);

      // Risk Level Rating Section
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(13);
      doc.setTextColor(24, 24, 27);
      doc.text('Executive Summary', 15, 110);

      // Risk Score Badge Card
      doc.setFillColor(244, 244, 245);
      doc.rect(15, 116, 75, 48, 'F');
      
      // Left indicator strip
      doc.setFillColor(riskColor[0], riskColor[1], riskColor[2]);
      doc.rect(15, 116, 4, 48, 'F');

      doc.setTextColor(82, 82, 91);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('OVERALL RISK', 24, 125);

      doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
      doc.setFontSize(16);
      doc.text(overallRisk, 24, 137);

      doc.setFontSize(9);
      doc.setTextColor(113, 113, 122);
      doc.text('Threat classification', 24, 150);

      // Key Metrics Box
      doc.setFillColor(244, 244, 245);
      doc.rect(98, 116, pageWidth - 113, 48, 'F');
      
      doc.setTextColor(82, 82, 91);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('FINDINGS METRICS', 104, 125);

      doc.setTextColor(24, 24, 27);
      doc.text(`• Total Issues Flagged: ${results.length}`, 104, 134);
      doc.text(`• Requires Patch: ${results.filter(r => r.secureCode).length}`, 104, 140);
      doc.text(`• Status: Needs Review`, 104, 146);

      // Summary details text
      doc.setTextColor(82, 82, 91);
      doc.setFont('Helvetica', 'normal');
      doc.setFontSize(10);
      const summaryText = results.length > 0
        ? `The static and dynamic path audit has flagged ${results.length} security vulnerability vulnerabilities that require immediate code remediation to secure database entries, inputs, or headers. Please inspect the code fixes and deploy patches.`
        : `Excellent! The static and dynamic analysis has completed successfully and found no common threat vulnerabilities in your scanned context. All security checks pass!`;
      
      const splitSummary = doc.splitTextToSize(summaryText, pageWidth - 30);
      doc.text(splitSummary, 15, 178);

      // PAGE 2: VULNERABILITY DETAIL
      doc.addPage();
      drawHeaderFooter(2, 2);

      doc.setTextColor(24, 24, 27);
      doc.setFont('Helvetica', 'bold');
      doc.setFontSize(14);
      doc.text('Detailed Security Findings', 15, 32);

      let currentY = 40;

      if (results.length === 0) {
        doc.setFillColor(244, 244, 245);
        doc.rect(15, currentY, pageWidth - 30, 20, 'F');
        doc.setFont('Helvetica', 'normal');
        doc.setTextColor(82, 82, 91);
        doc.text('No vulnerabilities or security issues were found.', 20, currentY + 12);
      } else {
        results.forEach((finding, idx) => {
          // Check if space remains on the page, add page if near bottom
          if (currentY > pageHeight - 65) {
            doc.addPage();
            drawHeaderFooter(doc.getNumberOfPages(), doc.getNumberOfPages());
            currentY = 30;
          }

          // Border wrapper
          doc.setFillColor(252, 252, 252);
          doc.setDrawColor(228, 228, 231);
          doc.rect(15, currentY, pageWidth - 30, 52, 'FD');

          // Title & severity badge color
          let sevColor = [59, 130, 246]; // Blue
          if (finding.severity === 'CRITICAL') sevColor = [239, 68, 68];
          else if (finding.severity === 'HIGH') sevColor = [249, 115, 22];
          else if (finding.severity === 'MEDIUM') sevColor = [234, 179, 8];

          // Indicator bar
          doc.setFillColor(sevColor[0], sevColor[1], sevColor[2]);
          doc.rect(15, currentY, 3, 52, 'F');

          // Finding Title
          doc.setTextColor(24, 24, 27);
          doc.setFont('Helvetica', 'bold');
          doc.setFontSize(10);
          doc.text(`${idx + 1}. ${finding.name}`, 22, currentY + 7);

          // Path & Severity
          doc.setFont('Helvetica', 'normal');
          doc.setTextColor(113, 113, 122);
          doc.setFontSize(8.5);
          doc.text(`Severity: ${finding.severity}    |    Path: ${finding.filePath || 'Manual Code Context'}`, 22, currentY + 13);

          // Explanation
          doc.setTextColor(63, 63, 70);
          const explLines = doc.splitTextToSize(finding.explanation, pageWidth - 45);
          doc.text(explLines, 22, currentY + 20);

          // Code reference label
          doc.setTextColor(39, 39, 42);
          doc.setFont('Helvetica', 'bold');
          const snippetText = `Vulnerable Snippet:  ${finding.vulnerableCode.substring(0, 75).trim()}${finding.vulnerableCode.length > 75 ? '...' : ''}`;
          doc.text(snippetText, 22, currentY + 45);

          currentY += 58;
        });
      }

      // Save document
      const cleanName = (targetName || 'Snippet').replace(/[^a-z0-9]/gi, '-').toLowerCase();
      doc.save(`BugZ-Security-Audit-${cleanName}-${Date.now().toString().slice(-6)}.pdf`);
      
      // GA4 Telemetry event
      trackEvent('pdf_downloaded');
    } catch (error) {
      console.error('PDF creation error:', error);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button
      onClick={generatePDF}
      disabled={generating}
      className="flex items-center space-x-2 py-2 px-3.5 rounded-lg bg-zinc-800 hover:bg-zinc-700 disabled:bg-zinc-850 border border-zinc-700 disabled:border-zinc-800 text-xs font-semibold text-zinc-300 disabled:text-zinc-550 transition"
      title="Download PDF Report"
    >
      {generating ? (
        <>
          <Loader2 className="h-4 w-4 animate-spin text-emerald-500" />
          <span>Generating PDF...</span>
        </>
      ) : (
        <>
          <Download className="h-4 w-4" />
          <span>Download PDF Report</span>
        </>
      )}
    </button>
  );
}
